angular.module('flatpcApp')
.controller('VisitCtrl', ['$scope', '$state','AppConfig','$rootScope',function($scope, $state,AppConfig,$rootScope) {
    $scope.name = $state.current.name;
    $scope.tree = [
        {
            name:'树枝1',
            list:[
                {
                    name:'树枝2',
                    list:[
                        {
                            name:"树枝3",
                            list:[
                                {
                                    name:'树枝4',
                                    list:[
                                        {
                                            name:'树枝5',
                                            list:[
                                                {
                                                    name:'叶子6'
                                                }
                                            ]
                                        },
                                        {
                                            name:'叶子5'
                                        }
                                    ]
                                },
                                {
                                    name:'叶子4'
                                }
                            ]
                        },
                        {
                            name:"叶子3"
                        },
                        {
                            name:"叶子3"
                        }
                    ]
                },
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        },
                        {
                            name:"叶子"
                        }
                    ]
                },
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                }
            ]
        },
        {
            name:'树枝',
            list:[
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                },
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                },
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                }
            ]
        },
        {
            name:'树枝',
            list:[
                {
                    name:'叶子'
                }
            ]
        },
        {
            name:'叶子'
        },
        {
            name:'树枝',
            list:[
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                }
            ]
        },
        {
            name:'树枝',
            list:[
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                }
            ]
        },
        {
            name:'树枝',
            list:[
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                }
            ]
        },
        {
            name:'树枝',
            list:[
                {
                    name:'树枝',
                    list:[
                        {
                            name:"叶子"
                        }
                    ]
                }
            ]
        }
        
    ]
    $rootScope.loading = false;
    $scope.datepickerOptions ={
        format: 'yyyy-mm-dd',
        language: 'ch',
        autoclose: true,
        weekStart: 0
    }
    console.log($scope.name);
}]);